# Generated by Django 4.2.4 on 2023-08-29 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mechanic',
            name='employee',
        ),
        migrations.AlterField(
            model_name='mechanic',
            name='phone',
            field=models.CharField(max_length=20),
        ),
    ]
