# Generated by Django 4.2.4 on 2023-09-06 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0002_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='valid',
            field=models.BooleanField(default=True),
        ),
    ]
