# Generated by Django 4.2.4 on 2023-08-31 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0002_remove_mechanic_employee_alter_mechanic_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='inprogress',
            field=models.BooleanField(default=False),
        ),
    ]
