# Generated by Django 4.2.4 on 2023-09-06 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0003_coupon_valid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mechanic',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
