INSERT INTO admin.logentry (action_time, user, content_type, object_id, object_repr, action_flag, change_message) VALUES ("2023-10-01T20:49:22.379Z", "1", "4", "2", "cliente", "1", "[{"added": {}}]");
INSERT INTO admin.logentry (action_time, user, content_type, object_id, object_repr, action_flag, change_message) VALUES ("2023-10-01T20:50:24.790Z", "1", "4", "2", "cliente", "2", "[{"changed": {"fields": ["First name", "Last name", "Email address", "Groups"]}}]");
INSERT INTO admin.logentry (action_time, user, content_type, object_id, object_repr, action_flag, change_message) VALUES ("2023-10-01T20:50:44.097Z", "1", "4", "3", "recepcionista", "1", "[{"added": {}}]");
INSERT INTO admin.logentry (action_time, user, content_type, object_id, object_repr, action_flag, change_message) VALUES ("2023-10-01T20:51:01.152Z", "1", "4", "3", "recepcionista", "2", "[{"changed": {"fields": ["First name", "Last name", "Email address", "Groups"]}}]");
INSERT INTO admin.logentry (action_time, user, content_type, object_id, object_repr, action_flag, change_message) VALUES ("2023-10-01T20:51:16.458Z", "1", "8", "1", "08:00 AM", "1", "[{"added": {}}]");
INSERT INTO admin.logentry (action_time, user, content_type, object_id, object_repr, action_flag, change_message) VALUES ("2023-10-01T20:51:25.282Z", "1", "8", "2", "13:00 PM", "1", "[{"added": {}}]");
INSERT INTO admin.logentry (action_time, user, content_type, object_id, object_repr, action_flag, change_message) VALUES ("2023-10-01T20:51:42.100Z", "1", "10", "1", "Alan Brito", "1", "[{"added": {}}]");
INSERT INTO admin.logentry (action_time, user, content_type, object_id, object_repr, action_flag, change_message) VALUES ("2023-10-01T20:52:17.257Z", "1", "11", "1", "1. Servicio diagnóstico $10,000 pesos", "1", "[{"added": {}}]");
INSERT INTO admin.logentry (action_time, user, content_type, object_id, object_repr, action_flag, change_message) VALUES ("2023-10-01T20:52:28.387Z", "1", "11", "2", "2. Cambio de Frenos $50,000 pesos", "1", "[{"added": {}}]");
INSERT INTO admin.logentry (action_time, user, content_type, object_id, object_repr, action_flag, change_message) VALUES ("2023-10-01T20:52:38.973Z", "1", "11", "3", "3. Cambio líquido frenos y purga $30,000 pesos", "1", "[{"added": {}}]");
INSERT INTO admin.logentry (action_time, user, content_type, object_id, object_repr, action_flag, change_message) VALUES ("2023-10-01T20:52:48.974Z", "1", "11", "4", "4. Cambio bujía x1 $10,000 pesos", "1", "[{"added": {}}]");
INSERT INTO admin.logentry (action_time, user, content_type, object_id, object_repr, action_flag, change_message) VALUES ("2023-10-01T20:53:01.707Z", "1", "11", "5", "5. Cambio de aceite $20,000 pesos", "1", "[{"added": {}}]");
INSERT INTO admin.logentry (action_time, user, content_type, object_id, object_repr, action_flag, change_message) VALUES ("2023-10-01T20:53:17.229Z", "1", "11", "6", "6. Cambio de neumáticos $40,000 pesos", "1", "[{"added": {}}]");
INSERT INTO admin.logentry (action_time, user, content_type, object_id, object_repr, action_flag, change_message) VALUES ("2023-10-01T20:53:26.854Z", "1", "11", "7", "7. Alineación y Balanceo $20,000 pesos", "1", "[{"added": {}}]");
INSERT INTO admin.logentry (action_time, user, content_type, object_id, object_repr, action_flag, change_message) VALUES ("2023-10-01T20:53:38.339Z", "1", "11", "8", "8. Cambio de correa $80,000 pesos", "1", "[{"added": {}}]");
INSERT INTO admin.logentry (action_time, user, content_type, object_id, object_repr, action_flag, change_message) VALUES ("2023-10-01T20:54:02.676Z", "1", "13", "1", "Taller Automotriz Maipú. Maipú, Calle Saturno # 999", "1", "[{"added": {}}]");
INSERT INTO admin.logentry (action_time, user, content_type, object_id, object_repr, action_flag, change_message) VALUES ("2023-10-01T20:54:15.572Z", "1", "12", "1", "En espera", "1", "[{"added": {}}]");
INSERT INTO admin.logentry (action_time, user, content_type, object_id, object_repr, action_flag, change_message) VALUES ("2023-10-01T20:54:21.284Z", "1", "12", "2", "En diagnóstico", "1", "[{"added": {}}]");
INSERT INTO admin.logentry (action_time, user, content_type, object_id, object_repr, action_flag, change_message) VALUES ("2023-10-01T20:54:27.191Z", "1", "12", "3", "En espera confirmación de presupuesto", "1", "[{"added": {}}]");
INSERT INTO admin.logentry (action_time, user, content_type, object_id, object_repr, action_flag, change_message) VALUES ("2023-10-01T20:54:35.315Z", "1", "12", "4", "En mantención", "1", "[{"added": {}}]");
INSERT INTO admin.logentry (action_time, user, content_type, object_id, object_repr, action_flag, change_message) VALUES ("2023-10-01T20:54:42.251Z", "1", "12", "5", "En espera de repuesto", "1", "[{"added": {}}]");
INSERT INTO admin.logentry (action_time, user, content_type, object_id, object_repr, action_flag, change_message) VALUES ("2023-10-01T20:54:48.113Z", "1", "12", "6", "Listo para entrega", "1", "[{"added": {}}]");
INSERT INTO admin.logentry (action_time, user, content_type, object_id, object_repr, action_flag, change_message) VALUES ("2023-10-01T20:54:53.233Z", "1", "12", "7", "Finalizado", "1", "[{"added": {}}]");
INSERT INTO admin.logentry (action_time, user, content_type, object_id, object_repr, action_flag, change_message) VALUES ("2023-10-01T20:54:57.801Z", "1", "12", "8", "Cancelado", "1", "[{"added": {}}]");
INSERT INTO auth.permission (name, content_type, codename) VALUES ("Can add log entry", "1", "add_logentry");
INSERT INTO auth.permission (name, content_type, codename) VALUES ("Can change log entry", "1", "change_logentry");
INSERT INTO auth.permission (name, content_type, codename) VALUES ("Can delete log entry", "1", "delete_logentry");
INSERT INTO auth.permission (name, content_type, codename) VALUES ("Can view log entry", "1", "view_logentry");
INSERT INTO auth.permission (name, content_type, codename) VALUES ("Can add permission", "2", "add_permission");
INSERT INTO auth.permission (name, content_type, codename) VALUES ("Can change permission", "2", "change_permission");
INSERT INTO auth.permission (name, content_type, codename) VALUES ("Can delete permission", "2", "delete_permission");
INSERT INTO auth.permission (name, content_type, codename) VALUES ("Can view permission", "2", "view_permission");
INSERT INTO auth.permission (name, content_type, codename) VALUES ("Can add group", "3", "add_group");
INSERT INTO auth.permission (name, content_type, codename) VALUES ("Can change group", "3", "change_group");
INSERT INTO auth.permission (name, content_type, codename) VALUES ("Can delete group", "3", "delete_group");
INSERT INTO auth.permission (name, content_type, codename) VALUES ("Can view group", "3", "view_group");
INSERT INTO auth.permission (name, content_type, codename) VALUES ("Can add user", "4", "add_user");
INSERT INTO auth.permission (name, content_type, codename) VALUES ("Can change user", "4", "change_user");
INSERT INTO auth.permission (name, content_type, codename) VALUES ("Can delete user", "4", "delete_user");
INSERT INTO auth.permission (name, content_type, codename) VALUES ("Can view user", "4", "view_user");
INSERT INTO auth.permission (name, content_type, codename) VALUES ("Can add content type", "5", "add_contenttype");
INSERT INTO auth.permission (name, content_type, codename) VALUES ("Can change content type", "5", "change_contenttype");
INSERT INTO auth.permission (name, content_type, codename) VALUES ("Can delete content type", "5", "delete_contenttype");
INSERT INTO auth.permission (name, content_type, codename) VALUES ("Can view content type", "5", "view_contenttype");
INSERT INTO auth.permission (name, content_type, codename) VALUES ("Can add session", "6", "add_session");
INSERT INTO auth.permission (name, content_type, codename) VALUES ("Can change session", "6", "change_session");
INSERT INTO auth.permission (name, content_type, codename) VALUES ("Can delete session", "6", "delete_session");
INSERT INTO auth.permission (name, content_type, codename) VALUES ("Can view session", "6", "view_session");
INSERT INTO auth.permission (name, content_type, codename) VALUES ("Can add appointment", "7", "add_appointment");
INSERT INTO auth.permission (name, content_type, codename) VALUES ("Can change appointment", "7", "change_appointment");
INSERT INTO auth.permission (name, content_type, codename) VALUES ("Can delete appointment", "7", "delete_appointment");
INSERT INTO auth.permission (name, content_type, codename) VALUES ("Can view appointment", "7", "view_appointment");
INSERT INTO auth.permission (name, content_type, codename) VALUES ("Can add attention", "8", "add_attention");
INSERT INTO auth.permission (name, content_type, codename) VALUES ("Can change attention", "8", "change_attention");
INSERT INTO auth.permission (name, content_type, codename) VALUES ("Can delete attention", "8", "delete_attention");
INSERT INTO auth.permission (name, content_type, codename) VALUES ("Can view attention", "8", "view_attention");
INSERT INTO auth.permission (name, content_type, codename) VALUES ("Can add job", "9", "add_job");
INSERT INTO auth.permission (name, content_type, codename) VALUES ("Can change job", "9", "change_job");
INSERT INTO auth.permission (name, content_type, codename) VALUES ("Can delete job", "9", "delete_job");
INSERT INTO auth.permission (name, content_type, codename) VALUES ("Can view job", "9", "view_job");
INSERT INTO auth.permission (name, content_type, codename) VALUES ("Can add mechanic", "10", "add_mechanic");
INSERT INTO auth.permission (name, content_type, codename) VALUES ("Can change mechanic", "10", "change_mechanic");
INSERT INTO auth.permission (name, content_type, codename) VALUES ("Can delete mechanic", "10", "delete_mechanic");
INSERT INTO auth.permission (name, content_type, codename) VALUES ("Can view mechanic", "10", "view_mechanic");
INSERT INTO auth.permission (name, content_type, codename) VALUES ("Can add service", "11", "add_service");
INSERT INTO auth.permission (name, content_type, codename) VALUES ("Can change service", "11", "change_service");
INSERT INTO auth.permission (name, content_type, codename) VALUES ("Can delete service", "11", "delete_service");
INSERT INTO auth.permission (name, content_type, codename) VALUES ("Can view service", "11", "view_service");
INSERT INTO auth.permission (name, content_type, codename) VALUES ("Can add vehicle status", "12", "add_vehiclestatus");
INSERT INTO auth.permission (name, content_type, codename) VALUES ("Can change vehicle status", "12", "change_vehiclestatus");
INSERT INTO auth.permission (name, content_type, codename) VALUES ("Can delete vehicle status", "12", "delete_vehiclestatus");
INSERT INTO auth.permission (name, content_type, codename) VALUES ("Can view vehicle status", "12", "view_vehiclestatus");
INSERT INTO auth.permission (name, content_type, codename) VALUES ("Can add workshop", "13", "add_workshop");
INSERT INTO auth.permission (name, content_type, codename) VALUES ("Can change workshop", "13", "change_workshop");
INSERT INTO auth.permission (name, content_type, codename) VALUES ("Can delete workshop", "13", "delete_workshop");
INSERT INTO auth.permission (name, content_type, codename) VALUES ("Can view workshop", "13", "view_workshop");
INSERT INTO auth.permission (name, content_type, codename) VALUES ("Can add work", "14", "add_work");
INSERT INTO auth.permission (name, content_type, codename) VALUES ("Can change work", "14", "change_work");
INSERT INTO auth.permission (name, content_type, codename) VALUES ("Can delete work", "14", "delete_work");
INSERT INTO auth.permission (name, content_type, codename) VALUES ("Can view work", "14", "view_work");
INSERT INTO auth.permission (name, content_type, codename) VALUES ("Can add vehicle", "15", "add_vehicle");
INSERT INTO auth.permission (name, content_type, codename) VALUES ("Can change vehicle", "15", "change_vehicle");
INSERT INTO auth.permission (name, content_type, codename) VALUES ("Can delete vehicle", "15", "delete_vehicle");
INSERT INTO auth.permission (name, content_type, codename) VALUES ("Can view vehicle", "15", "view_vehicle");
INSERT INTO auth.permission (name, content_type, codename) VALUES ("Can add point", "16", "add_point");
INSERT INTO auth.permission (name, content_type, codename) VALUES ("Can change point", "16", "change_point");
INSERT INTO auth.permission (name, content_type, codename) VALUES ("Can delete point", "16", "delete_point");
INSERT INTO auth.permission (name, content_type, codename) VALUES ("Can view point", "16", "view_point");
INSERT INTO auth.permission (name, content_type, codename) VALUES ("Can add coupon", "17", "add_coupon");
INSERT INTO auth.permission (name, content_type, codename) VALUES ("Can change coupon", "17", "change_coupon");
INSERT INTO auth.permission (name, content_type, codename) VALUES ("Can delete coupon", "17", "delete_coupon");
INSERT INTO auth.permission (name, content_type, codename) VALUES ("Can view coupon", "17", "view_coupon");
INSERT INTO auth.permission (name, content_type, codename) VALUES ("Can add checklist", "18", "add_checklist");
INSERT INTO auth.permission (name, content_type, codename) VALUES ("Can change checklist", "18", "change_checklist");
INSERT INTO auth.permission (name, content_type, codename) VALUES ("Can delete checklist", "18", "delete_checklist");
INSERT INTO auth.permission (name, content_type, codename) VALUES ("Can view checklist", "18", "view_checklist");
INSERT INTO auth.group (name, permissions) VALUES ("Customer", "[]");
INSERT INTO auth.group (name, permissions) VALUES ("Recepcionist", "[]");
INSERT INTO auth.user (password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined, groups, user_permissions) VALUES ("pbkdf2_sha256$600000$uEOXvjP2iBFehgTx1ulvkY$tFd5/8RMMV5z9oLny8Gmckm5ejizG6w0fyPBcKDNknY=", "2023-10-01T20:48:34.550Z", "True", "admin", "", "", "admin@admin.com", "True", "True", "2023-10-01T20:48:18.862Z", "[]", "[]");
INSERT INTO auth.user (password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined, groups, user_permissions) VALUES ("pbkdf2_sha256$600000$uFxjiQREqFYkvH03C9PoOd$nVoqI8RxbbPuEo1gHJzeknfhPjT9hxa3f/L+CvtpR4I=", "None", "False", "cliente", "Juan", "Perez", "juan@gmail.com", "False", "True", "2023-10-01T20:49:22Z", "[1]", "[]");
INSERT INTO auth.user (password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined, groups, user_permissions) VALUES ("pbkdf2_sha256$600000$IcNWjFaHlFjvfJdMFGExUL$tWRA/aaIdU9oDp9Zp7iv+JHwBxyalZUuVNhNsLtY6jo=", "2023-10-01T20:55:14.785Z", "False", "recepcionista", "Sebastian", "López", "seba@gmail.com", "False", "True", "2023-10-01T20:50:43Z", "[2]", "[]");
INSERT INTO contenttypes.contenttype (app_label, model) VALUES ("admin", "logentry");
INSERT INTO contenttypes.contenttype (app_label, model) VALUES ("auth", "permission");
INSERT INTO contenttypes.contenttype (app_label, model) VALUES ("auth", "group");
INSERT INTO contenttypes.contenttype (app_label, model) VALUES ("auth", "user");
INSERT INTO contenttypes.contenttype (app_label, model) VALUES ("contenttypes", "contenttype");
INSERT INTO contenttypes.contenttype (app_label, model) VALUES ("sessions", "session");
INSERT INTO contenttypes.contenttype (app_label, model) VALUES ("Management", "appointment");
INSERT INTO contenttypes.contenttype (app_label, model) VALUES ("Management", "attention");
INSERT INTO contenttypes.contenttype (app_label, model) VALUES ("Management", "job");
INSERT INTO contenttypes.contenttype (app_label, model) VALUES ("Management", "mechanic");
INSERT INTO contenttypes.contenttype (app_label, model) VALUES ("Management", "service");
INSERT INTO contenttypes.contenttype (app_label, model) VALUES ("Management", "vehiclestatus");
INSERT INTO contenttypes.contenttype (app_label, model) VALUES ("Management", "workshop");
INSERT INTO contenttypes.contenttype (app_label, model) VALUES ("Management", "work");
INSERT INTO contenttypes.contenttype (app_label, model) VALUES ("Management", "vehicle");
INSERT INTO contenttypes.contenttype (app_label, model) VALUES ("Management", "point");
INSERT INTO contenttypes.contenttype (app_label, model) VALUES ("Management", "coupon");
INSERT INTO contenttypes.contenttype (app_label, model) VALUES ("Management", "checklist");
INSERT INTO sessions.session (session_data, expire_date) VALUES (".eJxVjEEOwiAQRe_C2hBgKIhL956BzDCjVA1NSrsy3l2bdKHb_977L5VxXWpeu8x5ZHVSoA6_G2F5SNsA37HdJl2mtswj6U3RO-36MrE8z7v7d1Cx12_tAxAhpGjIk02c7NH6kooE4cLOAw_I4J0Xwy6mdCVxAWJAgsEaCOr9AeSgN50:1qn3T8:_-cWBEpuUO7neJwOa2LGucAO1v_RBZa0STMtIlkSHP4", "2023-10-15T20:55:14.870Z");
INSERT INTO Management.workshop (name, address, num_addres) VALUES ("Taller Automotriz Maipú", "Maipú, Calle Saturno", "999");
INSERT INTO Management.mechanic (first_name, last_name, phone, specialty, image) VALUES ("Alan", "Brito", "123123123", "Mecánico", "mechanics/foto_personal.jpg");
INSERT INTO Management.attention (attention) VALUES ("08:00:00");
INSERT INTO Management.attention (attention) VALUES ("13:00:00");
INSERT INTO Management.service (name, price, earn_points) VALUES ("Servicio diagnóstico", "10000", "10");
INSERT INTO Management.service (name, price, earn_points) VALUES ("Cambio de Frenos", "50000", "50");
INSERT INTO Management.service (name, price, earn_points) VALUES ("Cambio líquido frenos y purga", "30000", "30");
INSERT INTO Management.service (name, price, earn_points) VALUES ("Cambio bujía x1", "10000", "5");
INSERT INTO Management.service (name, price, earn_points) VALUES ("Cambio de aceite", "20000", "15");
INSERT INTO Management.service (name, price, earn_points) VALUES ("Cambio de neumáticos", "40000", "40");
INSERT INTO Management.service (name, price, earn_points) VALUES ("Alineación y Balanceo", "20000", "15");
INSERT INTO Management.service (name, price, earn_points) VALUES ("Cambio de correa", "80000", "80");
INSERT INTO Management.vehiclestatus (status) VALUES ("En espera");
INSERT INTO Management.vehiclestatus (status) VALUES ("En diagnóstico");
INSERT INTO Management.vehiclestatus (status) VALUES ("En espera confirmación de presupuesto");
INSERT INTO Management.vehiclestatus (status) VALUES ("En mantención");
INSERT INTO Management.vehiclestatus (status) VALUES ("En espera de repuesto");
INSERT INTO Management.vehiclestatus (status) VALUES ("Listo para entrega");
INSERT INTO Management.vehiclestatus (status) VALUES ("Finalizado");
INSERT INTO Management.vehiclestatus (status) VALUES ("Cancelado");
